#!/usr/bin/env python3

from random import randint

n = 100
size = 10000
with open('vectors', 'wb') as f:
    for _ in range(n):
        for _ in range(size):
            x = randint(0, (1 << 32) - 1)
            b = x.to_bytes(4, 'little')
            f.write(b)